# Array Operations

In [22]:
import numpy as np

```
 # arithmatic operations
   +, -, *, /
```

In [26]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,0])

In [27]:
a1 + a2

array([ 7,  9, 11, 13,  5])

In [28]:
a1 - a2

array([-5, -5, -5, -5,  5])

In [29]:
a1 * a2

array([ 6, 14, 24, 36,  0])

In [30]:
a1 / a2

C:\Users\adity\AppData\Local\Temp\ipykernel_16552\108435935.py:1: RuntimeWarning: divide by zero encountered in divide
  a1 / a2


array([0.16666667, 0.28571429, 0.375     , 0.44444444,        inf])

In [34]:
arr3 = np.arange(1,26).reshape(5,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
arr3 + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

# deep and shallow capy

In [38]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

``` here below slice is a example of shallow copy ```

In [42]:
slice = 10 * arr[:5]
slice

array([10, 20, 30, 40, 50])

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
b = arr
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
b = 10+b
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40])

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[6,7]])

In [53]:
A
B

array([[5, 6],
       [6, 7]])

In [54]:
A

array([[1, 2],
       [3, 4]])

In [55]:
A @ B

array([[17, 20],
       [39, 46]])

In [56]:
np.dot(A,B)

array([[17, 20],
       [39, 46]])

In [57]:
A.T

array([[1, 3],
       [2, 4]])

# advanca array manipulation

 ``` -> Stacking array using two array. Only single dimenstion array can be stacked ```

In [65]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
c = np.array([8,9,10,11])

In [67]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

```
# spliting array
    there are two ways to split in horizontal and in vertical
    np.hsplit(array_name,half value of the array)
    np.vsplit(array_name,half value of the array)
```

In [83]:
d = np.arange(16).reshape(4,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
np.hsplit(d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [81]:
np.vsplit(d,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [82]:
for i in d:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
