# basic array creation


## importing numpy in array

In [5]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

## creating a multidimensional list using array

In [10]:
l = [[1,2,3],[10,20,30],[100,200,300]]
l

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [12]:
np.array(l)

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

## creating zeros and ones with  zeros and ones function

In [18]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr = np.ones((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## creating a linear scacing array using linspace function

In [25]:
arr = np.linspace(1,11,6)
arr

array([ 1.,  3.,  5.,  7.,  9., 11.])

# random number generation function

In [33]:
arr = np.random.rand(5)
arr


array([0.22588036, 0.55641903, 0.67676279, 0.14481507, 0.7756374 ])

In [36]:
arr = np.random.randn(10)
arr

array([-0.44504598,  0.14847953, -1.50302503, -0.03659594,  2.59948755,
       -0.38326702, -0.54957715,  1.47318622,  0.37716398, -2.24541351])

In [42]:
arr = np.random.randint(10,20,5)
arr

array([19, 10, 13, 13, 13], dtype=int32)

# array attributes

In [45]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.shape

(3, 3)

In [47]:
arr.size

9

In [49]:
arr.dtype

dtype('int64')

# array methods

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.min()

np.int64(1)

In [54]:
arr.max() # getting maximum num from array

np.int64(9)

In [55]:
arr.sum()

np.int64(45)

## column wise sum of multidimensional array

In [57]:
arr.sum(axis =0)

array([12, 15, 18])

## row wise sum of multidimensional array

In [58]:
arr.sum(axis=1)

array([ 6, 15, 24])

# reshaping and resizing

In [64]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Array indexing and slicing

In [68]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

indexing in array is same as indexing in list

In [70]:
arr[3]

np.int64(14)

In [71]:
arr[2::]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
arr[2:4]

array([13, 14])

In [73]:
arr[2::2]

array([13, 15, 17, 19])

In [74]:
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Numpy indexing and splicing in multidimensional array

In [81]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [84]:
arr[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [85]:
arr[0,0]

np.int64(1)

In [86]:
arr[4,0]

np.int64(21)

In [87]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [88]:
arr[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [90]:
arr[3: ,3:]


array([[19, 20],
       [24, 25],
       [29, 30]])

In [92]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

# Bool indexing

In [100]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [102]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [103]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])